[package]
name = "riichi-rust"
version = "2.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"